# Generated by Django 4.1 on 2022-08-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bannierer',
            field=models.ImageField(blank=True, height_field=25, max_length=25, upload_to='user_banner', verbose_name='Bannière', width_field=25),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field=25, max_length=25, upload_to='user_profile', verbose_name='Avatar', width_field=25),
        ),
    ]
