# Generated by Django 4.1 on 2022-08-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_de_la_matiere', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exercice',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.matiere'),
        ),
    ]
