# Generated by Django 4.1 on 2022-08-11 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_matiere_exercice_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50, unique=True)),
                ('Nombre_exerce', models.PositiveIntegerField(verbose_name="Nombre d'exercice")),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matiere')),
            ],
        ),
    ]
