# Generated by Django 4.1 on 2022-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='exercices',
            field=models.ManyToManyField(to='main.exercice'),
        ),
    ]
